mvc_dotnet/WebApplication.Web/Models/PlotPlant/Plot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Web.Models
{
    public class Plot
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "A name for your plot is required")]
        public string PlotName { get; set; }
        [Required(ErrorMessage = "A length for your plot is needed")]
        public int Length { get; set; }
        [Required(ErrorMessage = "A width for your plot is needed")]
        public int  Width { get; set; }
        [Required(ErrorMessage = "We need to know how much light your plot gets")]
        public string PlotExposure { get; set; }
        public int UserId { get; set; }
        public List<Plant> Plants { get; set; }

        public Plot()
        {
            this.Plants = new List<Plant>();
        }
    }
}

mvc_dotnet/WebApplication.Web/Controllers/PlotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Web.DAL;
using WebApplication.Web.Models;
using WebApplication.Web.Providers.Auth;

namespace WebApplication.Web.Controllers
{
    [AuthorizationFilter]
    public class PlotController : Controller
    {
        public static string ViewedPlot = "Auth_Plot_Id";

        private IPlotDAO plotDAO;
        private IPlantDAO plantDAO;
        private IPlantPlotDAO plantPlotDAO;

        public PlotController(IPlotDAO plotDAO, IPlantDAO plantDAO, IPlantPlotDAO plantPlotDAO)
        {
            this.plotDAO = plotDAO;
            this.plantDAO = plantDAO;
            this.plantPlotDAO = plantPlotDAO;
        }

        [HttpGet]
        public IActionResult CreatePlot()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePlot(Plot plot)
        {

            int userId = HttpContext.Session.GetInt32(SessionAuthProvider.UserId).Value;
            if (ModelState.IsValid)
            {
                int newPlotId = plotDAO.CreatePlot(userId, plot);
                HttpContext.Session.SetInt32("Auth_Plot_Id", newPlotId);
                return RedirectToAction("UserPlotInfo", "Account");
            }
            return View(plot);

        }

        [HttpGet]
        public IActionResult ViewPlot(int id)
        {
            ViewPlotVM vm = new ViewPlotVM();
            vm.Plot = plotDAO.GetPlotById(id);
            vm.RecommendedPlants = plantDAO.GetPlantsByExposure(vm.Plot.PlotExposure);
            vm.FullSunPlants = plantDAO.GetPlantsFullSun();
            vm.PartialSunPlants = plantDAO.GetPlantsPartialSun();
            vm.FullShadePlants = plantDAO.GetPlantsFullShade();
            vm.CanvasPlantInfo = plantPlotDAO.GetPlantPlotInfo(id);
            vm.ListAllPlants = plantDAO.GetAllPlants();
            HttpContext.Session.SetInt32("ViewedPlot", id);

            return View(vm);
        }

    }
}

mvc_dotnet/WebApplication.Web/Views/Plot/CreatePlot.cshtml
@model Plot
@{
    ViewData["Title"] = "CreatePlot";
}

<h2>Create Plot</h2>

<div>
    <div>

         <p>Tell us a bit about your plot, and we'll save it for later use.</p>

    </div>
    <div>
        <form asp-controller="Plot" asp-action="CreatePlot" method="post">
            <table>
                <tr>
                    <td>
                        <label asp-for="PlotName">Plot Name</label>
                        <span class="error" asp-validation-for="PlotName"></span>
                        <input asp-for="PlotName" /><label asp-for="Length"></label>
                        <span class="error" asp-validation-for="Length"></span>
                        <input asp-for="Length" />
                        <label asp-for="Width"></label>
                        <span class="error" asp-validation-for="Width"></span>
                        <input asp-for="Width" />
                        <label asp-for="PlotExposure">Plot Exposure</label>
                        <span class="error" asp-validation-for="PlotExposure"></span>
                        <select asp-for="PlotExposure">
                            <option value="Full Shade">Full Shade</option>
                            <option value="Partial Sun">Partial Sun</option>
                            <option value="Full Sun">Full Sun</option>
                        </select>
                        <input type="submit" value="Create Plot" class="btn btn-default" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

mvc_dotnet/WebApplication.Web/Views/Plot/ViewPlot.cshtml
@model ViewPlotVM
@{
    ViewData["Title"] = "ViewPlot";
}

<h2>Edit Plot</h2>
<p><a id=login-register asp-controller="Account" asp-action="UserPlotInfo">Return To Your Dashboard</a></p>
<div id="plot-info">
    <div id="plot-detail">
        <div id="view-plot-header">
            <h3 id="view-plot-h3">@Model.Plot.PlotName</h3>
            <h3 id="view-plot-dimensions">@Model.Plot.Length ft. by @Model.Plot.Width ft.</h3>
        </div>
        <div>
            <select asp-for="@Model.Plot.PlotExposure" id="exposureList" onchange="changeRecommendedList();">
                <option value="Full Shade">Full Shade</option>
                <option value="Partial Sun">Partial Sun</option>
                <option value="Full Sun">Full Sun</option>
            </select>
        </div>
    </div>
</div>
<div id="main-content">
    <div id="planner">
        <canvas id="drawarea" width="@(Model.Plot.Length * 50) px" height="@(Model.Plot.Width * 50) px" style="border:2px solid black"></canvas>
        <button id="delete"> Delete Selected Plant </button>

        <button onclick="saveCanvas(canvas, '@Model')"> Save This Plot </button>  
    </div>
    <div id="recommendations" class="show-recommendations">
        @{ int i = 1;}
        @foreach (Plant plant in Model.RecommendedPlants)
        {
            <div>
                <a style="color: @plant.Color"
                   href="javascript:setPlantInfo('@plant.PlantName', '@plant.PlantExposure', '@plant.Spread', '@plant.Description', '@plant.Image')">
                    @(i). @plant.PlantName
                </a>
                <button id="addPlot" onclick="onAddPlot('@i', '@plant.Id', '@plant.Spread', '@plant.Color')">(Add)</button>
            </div>
            i++;
        }
    </div>
    <div class="secondary-recommendations hide-recommendations" id="Full Shade">
        @{i = 1;}
        @foreach (Plant plant in Model.FullShadePlants)
        {
            <div>
                <a style="color: @plant.Color"
                   href="javascript:setPlantInfo('@plant.PlantName', '@plant.PlantExposure', '@plant.Spread', '@plant.Description', '@plant.Image')">
                    @(i). @plant.PlantName
                </a>
                <button id="addPlot" onclick="onAddPlot('@i','@plant.Id', '@plant.Spread', '@plant.Color')">(Add)</button>
            </div>
            i++;
        }
    </div>
    <div class="secondary-recommendations hide-recommendations" id="Full Sun">
        @{i = 1;}
        @foreach (Plant plant in Model.FullSunPlants)
        {
            <div>
                <a style="color: @plant.Color"
                   href="javascript:setPlantInfo('@plant.PlantName', '@plant.PlantExposure', '@plant.Spread', '@plant.Description', '@plant.Image')">
                    @(i). @plant.PlantName
                </a>
                <button id="addPlot" onclick="onAddPlot('@i', '@plant.Id', '@plant.Spread', '@plant.Color')">(Add)</button>
            </div>
            i++;
        }
    </div>
    <div class="secondary-recommendations hide-recommendations" id="Partial Sun">
        @{i = 1;}
        @foreach (Plant plant in Model.PartialSunPlants)
        {
            <div>
                <a style="color: @plant.Color"
                   href="javascript:setPlantInfo('@plant.PlantName', '@plant.PlantExposure', '@plant.Spread', '@plant.Description', '@plant.Image')">
                    @(i). @plant.PlantName
                </a>
                <button id="addPlot" onclick="onAddPlot('@i','@plant.Id', '@plant.Spread', '@plant.Color')">(Add)</button>
            </div>
            i++;
        }
    </div>
</div>

<div id="plant-info" class="plant-info-hide">
    <div id="plant-image"></div>
    <div id="plant-details">
        <div id="plant-name"></div>
        <div id="plant-exposure"></div>
        <div id="plant-spread"></div>
        <div id="plant-description"></div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.2.0/fabric.min.js"></script>

<script type="text/javascript">
    
    let myTestData = @Html.Raw(Json.Serialize(@Model));



    function setPlantInfo(name, exposure, spread, description, image) {
        document.querySelector('div#plant-info').classList.remove("plant-info-hide");
        document.querySelector('div#plant-info').classList.add("plant-info-show");
        document.querySelector('div#plant-name').innerHTML = name;
        document.querySelector('div#plant-exposure').innerHTML = exposure;
        document.querySelector('div#plant-spread').innerHTML = "Spread: " + spread + " inches";
        document.querySelector('div#plant-description').innerHTML = description;
        document.querySelector('div#plant-image').innerHTML = '<img id="image"src="../../images/' + image + '"/>';
    };
</script>